import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'wael',
      email: 'admin@example.com',
      password: bcrypt.hashSync('wael'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

    products: [
      {
        name: 'LG C1 OLED',
        slug: 'LG-C1-OLED',
        category: 'TV',
        image: '/images/p1.jpg', 
        price: 1080,
        countInStock: 5,
        brand: 'lg',
        rating: 4.5,
        numReviews: 225,
        description: 'high quality TV',
      },
      {
        name: 'Hisense U8G',
        slug: 'Hisense-U8G',
        category: 'TV',
        image: '/images/p2.jpg',
        price: 650,
        countInStock: 20,
        brand: 'Hisense',
        rating: 4.2,
        numReviews: 150,
        description: 'mid range product',
      },
      {
        name: 'Sony A90J OLED',
        slug: 'Sony-A90J-OLED',
        category: 'TV',
        image: '/images/p3.jpg',
        price: 1950,
        countInStock: 15,
        brand: 'sony',
        rating: 4.6,
        numReviews: 198,
        description: 'high quality product',
      },
      {
        name: 'Samsung QN90A QLED',
        slug: 'Samsung-QN90A-QLED',
        category: 'TV',
        image: '/images/p4.jpg',
        price: 920,
        countInStock: 5,
        brand: 'samsung',
        rating: 4.5,
        numReviews: 210,
        description: 'high quality product',
      },
      {
        name: 'PS5',
        slug: 'PS5',
        category: 'console',
        image: '/images/p5.jpg', 
        price: 500,
        countInStock: 4,
        brand: 'PLAYSTATION',
        rating: 4.7,
        numReviews: 1230,
        description: 'GAME CONSOLE',
      },
      {
        name: 'PS4',
        slug: 'PS4',
        category: 'console',
        image: '/images/p6.jpg', 
        price: 250,
        countInStock: 12,
        brand: 'PLAYSTATION',
        rating: 4.1,
        numReviews: 1570,
        description: 'GAME CONSOLE',
      },
      {
        name: 'XBOX ONE',
        slug: 'XBOX-ONE',
        category: 'console',
        image: '/images/p7.jpg', 
        price: 250,
        countInStock: 7,
        brand: 'XBOX',
        rating: 4,
        numReviews: 924,
        description: 'GAME CONSOLE',
      },
      {
        name: 'XBOX SERIES X',
        slug: 'XBOX-SERIES-X',
        category: 'console',
        image: '/images/p8.jpg', 
        price: 500,
        countInStock: 3,
        brand: 'XBOX',
        rating: 4.4,
        numReviews: 733,
        description: 'GAME CONSOLE',
      },
    ],
  };

  export default data;
  